const fs = require('fs');

const items = [
  { id: "95040", codigo: "95040", artigo: "ANTT art. 30", descricao: "O condutor não adotar, em caso de sinistro, avaria ou outro fato que obrigue a imobilização do veículo, as providências constantes no Envelope para Transporte, conforme art. 30", gravidade: "ANTT", pontos: 0, valor: "Consultar ANTT", penalidade: "Multa ANTT", medidaAdministrativa: "Retenção", competencia: "ANTT / Órgão Rodoviário", infrator: "Condutor", exemplosObservacao: [] },
  { id: "95121", codigo: "95121", artigo: "ANTT", descricao: "Transportar produtos perigosos em veículo desprovido do conjunto de equipamentos para situações de emergência", gravidade: "ANTT", pontos: 0, valor: "Consultar ANTT", penalidade: "Multa ANTT", medidaAdministrativa: "Retenção", competencia: "ANTT / Órgão Rodoviário", infrator: "Transportador", exemplosObservacao: [] },
  { id: "95122", codigo: "95122", artigo: "ANTT", descricao: "Transportar produtos perigosos em veículo portando qualquer um dos componentes do conjunto de situação de emergência em condições inadequadas de uso", gravidade: "ANTT", pontos: 0, valor: "Consultar ANTT", penalidade: "Multa ANTT", medidaAdministrativa: "Retenção", competencia: "ANTT / Órgão Rodoviário", infrator: "Transportador", exemplosObservacao: [] },
  { id: "95201", codigo: "95201", artigo: "ANTT", descricao: "Transportar produtos perigosos em veículo desprovido dos conjuntos de EPIs necessários", gravidade: "ANTT", pontos: 0, valor: "Consultar ANTT", penalidade: "Multa ANTT", medidaAdministrativa: "Retenção", competencia: "ANTT / Órgão Rodoviário", infrator: "Transportador", exemplosObservacao: [] },
  { id: "95202", codigo: "95202", artigo: "ANTT", descricao: "Transportar produtos perigosos em veículo portando qualquer um dos componentes dos EPIs em condições inadequadas de uso", gravidade: "ANTT", pontos: 0, valor: "Consultar ANTT", penalidade: "Multa ANTT", medidaAdministrativa: "Retenção", competencia: "ANTT / Órgão Rodoviário", infrator: "Transportador", exemplosObservacao: [] },
  { id: "95391", codigo: "95391", artigo: "ANTT", descricao: "Transportar produtos perigosos em embalagens que apresentem sinais de violação", gravidade: "ANTT", pontos: 0, valor: "Consultar ANTT", penalidade: "Multa ANTT", medidaAdministrativa: "Retenção", competencia: "ANTT / Órgão Rodoviário", infrator: "Expedidor", exemplosObservacao: [] },
  { id: "95392", codigo: "95392", artigo: "ANTT", descricao: "Transportar produtos perigosos em embalagens que apresentem sinais de deterioração ou mau estado de conservação", gravidade: "ANTT", pontos: 0, valor: "Consultar ANTT", penalidade: "Multa ANTT", medidaAdministrativa: "Retenção", competencia: "ANTT / Órgão Rodoviário", infrator: "Expedidor", exemplosObservacao: [] },
  { id: "95471", codigo: "95471", artigo: "ANTT", descricao: "Transportar produtos perigosos em via restrita pela autoridade com circunscrição sobre a via", gravidade: "ANTT", pontos: 0, valor: "Consultar ANTT", penalidade: "Multa ANTT", medidaAdministrativa: "Retenção", competencia: "ANTT / Órgão Rodoviário", infrator: "Condutor", exemplosObservacao: [] },
  { id: "95472", codigo: "95472", artigo: "ANTT", descricao: "Estacionar ou parar em local ou período restrito pela autoridade com circunscrição sobre a via", gravidade: "ANTT", pontos: 0, valor: "Consultar ANTT", penalidade: "Multa ANTT", medidaAdministrativa: "Retenção", competencia: "ANTT / Órgão Rodoviário", infrator: "Condutor", exemplosObservacao: [] },
  { id: "95473", codigo: "95473", artigo: "ANTT", descricao: "Realizar carga em local ou período restrito pela autoridade com circunscrição sobre a via", gravidade: "ANTT", pontos: 0, valor: "Consultar ANTT", penalidade: "Multa ANTT", medidaAdministrativa: "Retenção", competencia: "ANTT / Órgão Rodoviário", infrator: "Condutor", exemplosObservacao: [] },
  { id: "95474", codigo: "95474", artigo: "ANTT", descricao: "Realizar descarga em local ou período restrito pela autoridade com circunscrição sobre a via", gravidade: "ANTT", pontos: 0, valor: "Consultar ANTT", penalidade: "Multa ANTT", medidaAdministrativa: "Retenção", competencia: "ANTT / Órgão Rodoviário", infrator: "Condutor", exemplosObservacao: [] },
  { id: "95550", codigo: "95550", artigo: "ANTT art. 20", descricao: "Estacionar veículo contendo produtos perigosos em desacordo ao art. 20", gravidade: "ANTT", pontos: 0, valor: "Consultar ANTT", penalidade: "Multa ANTT", medidaAdministrativa: "Retenção", competencia: "ANTT / Órgão Rodoviário", infrator: "Condutor", exemplosObservacao: [] },
  { id: "95631", codigo: "95631", artigo: "ANTT", descricao: "Abrir volumes contendo produtos perigosos durante as etapas da operação de transporte", gravidade: "ANTT", pontos: 0, valor: "Consultar ANTT", penalidade: "Multa ANTT", medidaAdministrativa: "Retenção", competencia: "ANTT / Órgão Rodoviário", infrator: "Condutor", exemplosObservacao: [] },
  { id: "95632", codigo: "95632", artigo: "ANTT", descricao: "Fumar durante as etapas da operação de transporte", gravidade: "ANTT", pontos: 0, valor: "Consultar ANTT", penalidade: "Multa ANTT", medidaAdministrativa: "Retenção", competencia: "ANTT / Órgão Rodoviário", infrator: "Condutor", exemplosObservacao: [] },
  { id: "95633", codigo: "95633", artigo: "ANTT", descricao: "Adentrar áreas de carga do veículo ou equipamento de transp com dispositivos capazes de produzir ignição dos produtos, gases ou vapores durante as etapas da operação de transp", gravidade: "ANTT", pontos: 0, valor: "Consultar ANTT", penalidade: "Multa ANTT", medidaAdministrativa: "Retenção", competencia: "ANTT / Órgão Rodoviário", infrator: "Condutor", exemplosObservacao: [] },
  { id: "95710", codigo: "95710", artigo: "ANTT art. 24", descricao: "Deixar, o condutor ou o auxiliar, de informar a imobilização do veículo à autoridade competente, conforme art. 24", gravidade: "ANTT", pontos: 0, valor: "Consultar ANTT", penalidade: "Multa ANTT", medidaAdministrativa: "Retenção", competencia: "ANTT / Órgão Rodoviário", infrator: "Condutor", exemplosObservacao: [] },
  { id: "95801", codigo: "95801", artigo: "ANTT", descricao: "Retirar a sinalização de veículo ou de equipamento de transporte que não tenha sido descontaminado", gravidade: "ANTT", pontos: 0, valor: "Consultar ANTT", penalidade: "Multa ANTT", medidaAdministrativa: "Retenção", competencia: "ANTT / Órgão Rodoviário", infrator: "Condutor", exemplosObservacao: [] },
  { id: "95802", codigo: "95802", artigo: "ANTT", descricao: "Retirar a Ficha de Emergência e o Envelope para Transporte de veículo que não tenha sido descontaminado", gravidade: "ANTT", pontos: 0, valor: "Consultar ANTT", penalidade: "Multa ANTT", medidaAdministrativa: "Retenção", competencia: "ANTT / Órgão Rodoviário", infrator: "Condutor", exemplosObservacao: [] },
  { id: "95980", codigo: "95980", artigo: "ANTT art. 3º", descricao: "Não retirar a sinalização dos veículos e equipamentos de transporte após as operações de limpeza e descontaminação, em desacordo ao parágrafo único do art. 3º", gravidade: "ANTT", pontos: 0, valor: "Consultar ANTT", penalidade: "Multa ANTT", medidaAdministrativa: "Retenção", competencia: "ANTT / Órgão Rodoviário", infrator: "Condutor", exemplosObservacao: [] }
];

let fileContent = fs.readFileSync('src/data/infractions.ts', 'utf-8');
const lastBracketIndex = fileContent.lastIndexOf(']');
if (lastBracketIndex !== -1) {
    const jsonString = JSON.stringify(items, null, 2);
    const innerItems = jsonString.slice(1, -1).trim();
    fileContent = fileContent.slice(0, lastBracketIndex) + ',\n  ' + innerItems + '\n' + fileContent.slice(lastBracketIndex);
    fs.writeFileSync('src/data/infractions.ts', fileContent);
    console.log('Added 19 ANTT items');
}
